### ISSUE TITLE
Occasional Service Launch Failure on Boot

### ISSUE THREAD

**Issue by Luishi5000** [MoshiMoshi0/TTController#44]
About 1 out of 3 times the service does not auto start on boot. It then starts manually no problem. Using 0.9.0-alpha.40.

Here is the log:

```
2020-05-05 20:45:36.5492|INFO|TTController.Service.TTService|================================================================
2020-05-05 20:45:36.5718|INFO|TTController.Service.TTService|Initializing...
2020-05-05 20:45:36.8645|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.DpsgController [0.9.0.0]
2020-05-05 20:45:36.8875|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RiingController [0.9.0.0]
2020-05-05 20:45:36.9055|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RiingPlusController [0.9.0.0]
2020-05-05 20:45:36.9226|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RiingTrioController [0.9.0.0]
2020-05-05 20:45:36.9396|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.AuroraEffect [0.9.0.0]
2020-05-05 20:45:36.9561|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.BlinkEffect [0.9.0.0]
2020-05-05 20:45:36.9721|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.CopyColorEffect [0.9.0.0]
2020-05-05 20:45:36.9886|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.FlowEffect [0.9.0.0]
2020-05-05 20:45:37.0051|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PingPongEffect [0.9.0.0]
2020-05-05 20:45:37.0216|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PulseEffect [0.9.0.0]
2020-05-05 20:45:37.0377|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RawEffect [0.9.0.0]
2020-05-05 20:45:37.0567|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RazerConnectEffect [0.9.0.0]
2020-05-05 20:45:37.0732|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RippleEffect [0.9.0.0]
2020-05-05 20:45:37.0902|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SensorEffect [0.9.0.0]
2020-05-05 20:45:37.1422|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SoundEffect [0.9.0.0]
2020-05-05 20:45:37.1588|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SpectrumEffect [0.9.0.0]
2020-05-05 20:45:37.1758|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.StaticColorEffect [0.9.0.0]
2020-05-05 20:45:37.1923|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.WaveEffect [0.9.0.0]
2020-05-05 20:45:37.2098|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.CopySpeedController [0.9.0.0]
2020-05-05 20:45:37.2268|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.DpsgSpeedController [0.9.0.0]
2020-05-05 20:45:37.2699|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PwmSpeedController [0.9.0.0]
2020-05-05 20:45:37.2874|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.StaticSpeedController [0.9.0.0]
2020-05-05 20:45:37.3039|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.AlwaysTrigger [0.9.0.0]
2020-05-05 20:45:37.3209|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.LogicTrigger [0.9.0.0]
2020-05-05 20:45:37.3369|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.OneTimeTrigger [0.9.0.0]
2020-05-05 20:45:37.3539|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.ProcessTrigger [0.9.0.0]
2020-05-05 20:45:37.3704|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PulseTrigger [0.9.0.0]
2020-05-05 20:45:37.3880|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.ScheduleTrigger [0.9.0.0]
2020-05-05 20:45:37.4050|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SensorTrigger [0.9.0.0]
2020-05-05 20:45:37.4120|INFO|TTController.Service.Managers.ConfigManager|Creating Config Manager...
2020-05-05 20:45:37.4720|INFO|TTController.Service.Managers.ConfigManager|Loading config...
2020-05-05 20:45:37.7337|INFO|TTController.Service.Utils.DataCache|Creating DataCache...
2020-05-05 20:45:37.7398|INFO|TTController.Service.Utils.PluginStore|Creating Plugin Store...
2020-05-05 20:45:37.7398|INFO|TTController.Service.Managers.SensorManager|Creating Sensor Manager...
2020-05-05 20:45:37.7398|INFO|TTController.Service.Hardware.LibreHardwareMonitorFacade|Initializing Libre Hardware Monitor...
2020-05-05 20:45:37.8652|INFO|TTController.Service.Managers.DeviceManager|Creating Device Manager...
2020-05-05 20:45:37.9322|INFO|TTController.Service.Managers.DeviceManager|Initialized "Riing Plus" controller [9802, 8101]
2020-05-05 20:45:37.9322|INFO|TTController.Service.Managers.SensorManager|Enabling sensor: /gpu/0/temperature/0
2020-05-05 20:45:37.9422|INFO|TTController.Service.Utils.PluginStore|Adding plugin "SensorEffect" [Default]
2020-05-05 20:45:37.9422|INFO|TTController.Service.Utils.PluginStore|Adding plugin "SoundEffect" [Default]
2020-05-05 20:45:37.9422|INFO|TTController.Service.Utils.PluginStore|Adding plugin "SensorEffect" [Default]
2020-05-05 20:45:37.9422|INFO|TTController.Service.Utils.PluginStore|Adding plugin "AuroraEffect" [Default]
2020-05-05 20:45:37.9422|INFO|TTController.Service.Utils.PluginStore|Adding plugin "SensorEffect" [Default]
2020-05-05 20:45:37.9567|INFO|TTController.Service.Utils.PluginStore|Adding plugin "PwmSpeedController" [Default]
2020-05-05 20:45:37.9723|INFO|TTController.Service.Managers.TimerManager|Creating Timer Manager...
2020-05-05 20:45:37.9723|INFO|TTController.Service.Managers.TimerManager|Starting 4 timers...
2020-05-05 20:45:37.9723|INFO|TTController.Service.TTService|Initializing done!
2020-05-05 20:45:37.9723|INFO|TTController.Service.TTService|================================================================
2020-05-05 21:16:09.4569|INFO|TTController.Service.TTService|================================================================
2020-05-05 21:16:09.4569|INFO|TTController.Service.TTService|Finalizing...
2020-05-05 21:16:09.4569|INFO|TTController.Service.Managers.TimerManager|Disposing Timer Manager...
2020-05-05 21:16:09.4569|INFO|TTController.Service.Managers.TimerManager|Stopping 4 timers...
2020-05-05 21:16:09.4804|INFO|TTController.Service.TTService|Applying computer state profile: Suspend
2020-05-05 21:16:09.4804|INFO|TTController.Service.Managers.SensorManager|Disposing Sensor Manager...
2020-05-05 21:16:09.4874|INFO|TTController.Service.Hardware.LibreHardwareMonitorFacade|Finalizing Libre Hardware Monitor...
2020-05-05 21:16:09.5299|INFO|TTController.Service.Managers.DeviceManager|Disposing Device Manager...
2020-05-05 21:16:09.5344|INFO|TTController.Service.Managers.ConfigManager|Disposing Config Manager...
2020-05-05 21:16:09.5344|INFO|TTController.Service.Utils.PluginStore|Disposing Plugin Store...
2020-05-05 21:16:09.5344|INFO|TTController.Service.Utils.PluginStore|Disposing plugin "SensorEffect" [Default]
2020-05-05 21:16:09.6308|INFO|TTController.Service.Utils.PluginStore|Disposing plugin "SoundEffect" [Default]
2020-05-05 21:16:09.6308|INFO|TTController.Service.Utils.PluginStore|Disposing plugin "SensorEffect" [Default]
2020-05-05 21:16:09.6308|INFO|TTController.Service.Utils.PluginStore|Disposing plugin "AuroraEffect" [Default]
2020-05-05 21:16:09.6308|INFO|TTController.Service.Utils.PluginStore|Disposing plugin "SensorEffect" [Default]
2020-05-05 21:16:09.6308|INFO|TTController.Service.Utils.PluginStore|Disposing plugin "PwmSpeedController" [Default]
2020-05-05 21:16:09.6473|INFO|TTController.Service.TTService|Finalizing done!
2020-05-05 21:16:10.0315|INFO|TTController.Service.TTService|================================================================
2020-05-06 08:06:01.8917|INFO|TTController.Service.TTService|================================================================
2020-05-06 08:06:01.8977|INFO|TTController.Service.TTService|Initializing...
2020-05-06 08:06:02.5152|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.DpsgController [0.9.0.0]
2020-05-06 08:06:02.5192|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RiingController [0.9.0.0]
2020-05-06 08:06:02.5192|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RiingPlusController [0.9.0.0]
2020-05-06 08:06:02.5192|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RiingTrioController [0.9.0.0]
2020-05-06 08:06:02.5192|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.AuroraEffect [0.9.0.0]
2020-05-06 08:06:02.5377|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.BlinkEffect [0.9.0.0]
2020-05-06 08:06:02.5377|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.CopyColorEffect [0.9.0.0]
2020-05-06 08:06:02.5377|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.FlowEffect [0.9.0.0]
2020-05-06 08:06:02.5507|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PingPongEffect [0.9.0.0]
2020-05-06 08:06:02.5507|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PulseEffect [0.9.0.0]
2020-05-06 08:06:02.5507|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RawEffect [0.9.0.0]
2020-05-06 08:06:02.5657|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RazerConnectEffect [0.9.0.0]
2020-05-06 08:06:02.5657|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.RippleEffect [0.9.0.0]
2020-05-06 08:06:02.5657|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SensorEffect [0.9.0.0]
2020-05-06 08:06:02.5657|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SoundEffect [0.9.0.0]
2020-05-06 08:06:02.5657|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SpectrumEffect [0.9.0.0]
2020-05-06 08:06:02.5843|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.StaticColorEffect [0.9.0.0]
2020-05-06 08:06:02.5843|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.WaveEffect [0.9.0.0]
2020-05-06 08:06:02.5843|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.CopySpeedController [0.9.0.0]
2020-05-06 08:06:02.5973|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.DpsgSpeedController [0.9.0.0]
2020-05-06 08:06:02.5973|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PwmSpeedController [0.9.0.0]
2020-05-06 08:06:02.5973|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.StaticSpeedController [0.9.0.0]
2020-05-06 08:06:02.5973|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.AlwaysTrigger [0.9.0.0]
2020-05-06 08:06:02.6123|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.LogicTrigger [0.9.0.0]
2020-05-06 08:06:02.6123|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.OneTimeTrigger [0.9.0.0]
2020-05-06 08:06:02.6123|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.ProcessTrigger [0.9.0.0]
2020-05-06 08:06:02.6123|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.PulseTrigger [0.9.0.0]
2020-05-06 08:06:02.6123|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.ScheduleTrigger [0.9.0.0]
2020-05-06 08:06:02.6298|INFO|TTController.Service.Utils.PluginLoader|Loading plugin assembly: TTController.Plugin.SensorTrigger [0.9.0.0]
2020-05-06 08:06:02.6298|INFO|TTController.Service.Managers.ConfigManager|Creating Config Manager...
2020-05-06 08:06:02.6843|INFO|TTController.Service.Managers.ConfigManager|Loading config...
2020-05-06 08:06:02.7799|FATAL|TTController.Service.Managers.ConfigManager|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> CSCore.CoreAudioAPI.CoreAudioAPIException: IAudioClient::IsFormatSupported caused an error: 0x80070003, "The system cannot find the path specified.".
   at CSCore.CoreAudioAPI.AudioClient.IsFormatSupported(AudioClientShareMode shareMode, WaveFormat waveFormat, WaveFormat& closestMatch)
   at CSCore.SoundIn.WasapiCapture.SetupWaveFormat(WaveFormat waveFormat, AudioClient audioClient)
   at CSCore.SoundIn.WasapiCapture.InitializeInternal()
   at CSCore.SoundIn.WasapiCapture.Initialize()
   at TTController.Plugin.SoundEffect.SoundEffect..ctor(SoundEffectConfig config) in C:\projects\ttcontroller\Plugins\Effects\TTController.Plugin.SoundEffect\SoundEffect.cs:line 32
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TTController.Service.Config.Converters.AbstractPluginConverter`2.ReadJson(JsonReader reader, Type objectType, TPlugin existingValue, Boolean hasExistingValue, JsonSerializer serializer) in C:\projects\ttcontroller\Source\TTController.Service\Config\Converters\AbstractPluginConverter.cs:line 39
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at TTController.Service.Managers.ConfigManager.LoadOrCreateConfig() in C:\projects\ttcontroller\Source\TTController.Service\Managers\ConfigManager.cs:line 87
2020-05-06 08:06:02.8185|FATAL|TTController.Service.Managers.ConfigManager|Failed to load the config!
2020-05-06 08:06:02.8185|FATAL|TTController.Service.TTService|System.Exception: Service failed to start!
   at TTController.Service.TTService.OnStart(String[] args) in C:\projects\ttcontroller\Source\TTController.Service\TTService.cs:line 123

```

**Current configuration**
```json
{
  "Profiles": [
    {
      "Name": "Default",
      "Ports": [
        [9802, 8101, 1],
        [9802, 8101, 2],
        [9802, 8101, 3]
      ],
      "SpeedControllers": [
        {
          "Type": "PwmSpeedController",
          "Config": {
            "CurvePoints": [
              [30, 30],
              [45, 50],
              [55, 60],
              [65, 80],
              [80, 100]
            ],
            "Sensors": ["/gpu/0/temperature/0"],
            "Trigger": {
              "Type": "AlwaysTrigger"
            }
          }
        }
      ],
      "Effects": [
        {
          "Type": "SensorEffect",
          "Config": {
            "Sensors": ["/gpu/0/temperature/0"],
            "ColorGradient": [
              [75, [0, 0, 0]],
              [80, [10, 0, 0]]
            ],
            "Trigger": {
              "Type": "ProcessTrigger",
              "Config": {
                  "Processes": ["wordpad"]
              }
            }
          }
        },
        {
          "Type": "SoundEffect",
          "Config": {
            "MinimumFrequency": 60,
            "MaximumFrequency": 100,
            "ScalingStrategy": "Sqrt",
            "ScalingFactor": 1.0,
            "ColorGradient": [
              [0, [255, 0, 0]],
              [0.2, [0, 0, 255]],
              [0.35, [255, 0, 0]],
              [0.5, [0, 255, 0]],
              [1, [255, 0, 255]]
            ],
            "Trigger": {
              "Type": "ProcessTrigger",
              "Config": {
                  "Processes": ["notepad"]
              }
            }
          }
        },
        {
          "Type": "SensorEffect",
          "Config": {
            "Sensors": ["/gpu/0/temperature/0"],
            "ColorGradient": [
              [62, [20, 0, 0]],
              [66, [40, 5, 0]],
              [75, [80, 0, 5]],
              [80, [255, 120, 0]]
            ],
            "Trigger": {
              "Type": "SensorTrigger",
              "Config": {
                  "Sensors": ["/gpu/0/temperature/0"],
                  "Value": 62
              }
            }
          }
        },
        {
          "Type": "AuroraEffect",
          "Config": {
            "Gradient": [
                [0.01, [220, 0, 0]],
                [0.02, [215, 5, 0]],
                [0.03, [200, 10, 0]],
                [0.04, [140, 80, 0]],
                [0.05, [20, 255, 30]],
                [0.06, [0, 140, 170]],
                [0.07, [0, 80, 200]],
                [0.08, [55, 60, 160]],
                [0.09, [180, 30, 60]],
                [0.10, [200, 2, 4]],
                [0.11, [220, 0, 1]],
                [0.12, [140, 50, 0]],
                [0.13, [140, 100, 0]],
                [0.14, [40, 140, 0]],
                [0.15, [70, 100, 2]],
                [0.16, [40, 80, 5]],
                [0.17, [35, 65, 20]],
                [0.18, [40, 55, 80]],
                [0.19, [50, 35, 100]],
                [0.20, [70, 70, 85]],
                [0.21, [77, 80, 75]],
                [0.22, [78, 81, 88]],
                [0.23, [79, 82, 89]],
                [0.24, [88, 100, 94]],
                [0.25, [96, 104, 105]],
                [0.26, [140, 165, 130]],
                [0.27, [175, 168, 179]],
                [0.28, [165, 210, 255]],
                [0.29, [90, 100, 255]],
                [0.30, [123, 192, 133]],
                [0.31, [139, 255, 144]],
                [0.32, [200, 210, 195]],
                [0.33, [230, 225, 232]],
                [0.34, [243, 241, 248]],
                [0.35, [255, 255, 255]],
                [0.36, [230, 223, 240]],
                [0.37, [200, 200, 200]],
                [0.38, [165, 160, 162]],
                [0.39, [130, 134, 132]],
                [0.40, [110, 115, 125]],
                [0.41, [102, 90, 110]],
                [0.42, [92, 80, 85]],
                [0.43, [91, 75, 65]],
                [0.44, [105, 70, 50]],
                [0.45, [120, 65, 45]],
                [0.46, [145, 55, 25]],
                [0.47, [170, 25, 0]],
                [0.48, [200, 5, 0]],
                [0.49, [220, 0, 0]],
                [0.50, [215, 5, 0]],
                [0.51, [200, 10, 0]],
                [0.52, [140, 80, 0]],
                [0.53, [20, 255, 30]],
                [0.54, [0, 140, 170]],
                [0.55, [0, 80, 200]],
                [0.56, [55, 60, 160]],
                [0.57, [180, 30, 60]],
                [0.58, [200, 2, 4]],
                [0.59, [220, 0, 1]],
                [0.60, [140, 50, 0]],
                [0.61, [140, 100, 0]],
                [0.62, [40, 140, 0]],
                [0.63, [70, 100, 2]],
                [0.64, [40, 80, 5]],
                [0.65, [35, 65, 20]],
                [0.66, [40, 55, 80]],
                [0.67, [50, 35, 100]],
                [0.68, [70, 70, 85]],
                [0.69, [77, 80, 75]],
                [0.70, [90, 70, 50]],
                [0.71, [120, 65, 45]],
                [0.72, [145, 55, 25]],
                [0.73, [170, 25, 0]],
                [0.74, [200, 5, 0]],
                [0.75, [220, 0, 0]],
                [0.76, [215, 5, 0]],
                [0.77, [200, 10, 0]],
                [0.78, [140, 90, 0]],
                [0.79, [20, 255, 30]],
                [0.80, [0, 140, 170]],
                [0.81, [0, 80, 200]],
                [0.82, [55, 60, 160]],
                [0.83, [180, 30, 60]],
                [0.84, [255, 2, 4]],
                [0.85, [220, 0, 1]],
                [0.86, [140, 50, 0]],
                [0.87, [140, 100, 0]],
                [0.88, [40, 140, 0]],
                [0.89, [70, 100, 2]],
                [0.90, [40, 80, 5]],
                [0.91, [35, 65, 20]],
                [0.92, [40, 35, 80]],
                [0.93, [50, 20, 100]],
                [0.94, [70, 70, 85]],
                [0.95, [77, 80, 75]],
                [0.96, [90, 70, 50]],
                [0.97, [120, 65, 45]],
                [0.98, [145, 55, 25]],
                [0.99, [170, 25, 0]],
                [1.0, [200, 5, 0]]

            ],
            "Step": 0.0001,
            "Length": 480,
            "Mirror": true,
            "Brightness": 1,
            "Saturation": 1,
            "ColorGenerationMethod": "SpanPorts",
            "Trigger": {
              "Type": "ScheduleTrigger",
              "Config": {
                  "Scope": "Day",
                  "Schedule": [
                      "08:00 -> 20:00"
                  ]
              }
            }
          }
        },
        {
          "Type": "SensorEffect",
          "Config": {
            "Sensors": ["/gpu/0/temperature/0"],
            "ColorGradient": [
              [47, [20, 0, 0]],
              [60, [125, 0, 0]],
              [75, [255, 0, 0]]
            ],
            "Trigger": {
              "Type": "AlwaysTrigger"
            }
          }
        }
      ]
    }
  ],
  "ComputerStateProfiles": [
    {
      "StateType": "Shutdown",
      "Ports": [
        [9802, 8101, 1],
        [9802, 8101, 2],
        [9802, 8101, 3]
      ],
      "Speed": 65,
      "EffectType": "Full",
      "EffectColors": [
        [128, 0, 0]
      ]
    }
  ],
  "PortConfigs": [
    {
      "Ports": [[9802, 8101, 1]],
      "Config": {
        "Name": "Top Fan"
      }
    }
  ],
  "SensorConfigs": [
    {
      "Sensors": ["/gpu/0/temperature/0"],
      "Config": {
        "CriticalValue": 90
      }
    }
  ]
}

```

**Comment by MoshiMoshi0** [comment]
I guess the service loads faster than it can access audio capture.
I'll see if I can delay initialization.

Thanks for reporting.

**Comment by MoshiMoshi0** [comment]
Try [this](https://ci.appveyor.com/project/MoshiMoshi0/ttcontroller/builds/32722754/artifacts) build.

It will constantly try to initialize if it fails it will just log the error. Not the best method but I could not find anything in cscore library that would be nicer.

**Comment by MoshiMoshi0** [comment]
Did you manage to test the above build? I would like to know if it helps.

**Comment by Luishi5000** [comment]
Tried it over the last few restarts - so far so good! Thanks for the new build, so nice not to have to start the service manually.
